### ISSUE TITLE
Other programming languages 

### ISSUE THREAD

**Issue by kassane** [georgik/esp32-lang-lab#10]
- https://wiki.freepascal.org/Xtensa | https://github.com/ccrause/fpc-esp-freertos/tree/v1.0
- https://github.com/kassane/zig-esp-idf-sample
- https://github.com/Reavershark/esp-dlang 

cc: @georgik

**Comment by georgik** [comment]
Hi @kassane . Thank you for those links. It would be awesome to have those languages there.
I would welcome if somebody can suggest CI script which can build and run the simulation for particular language with Wokwi to get those data.
CI Scripts are stored here: https://github.com/georgik/esp32-lang-lab/tree/main/.github/workflows

**Comment by kassane** [comment]
Currently I managed to get CMake to download the zig toolchain and run `esp-idf-ci` from espressif.
It may be possible to run it as a C example.

https://github.com/kassane/zig-esp-idf-sample/commit/30e94d2464b42cf89702d5b51e3e594479f988c6

**Comment by kassane** [comment]
Dlang wokwi test:
- https://github.com/Reavershark/esp-dlang/pull/3

**Comment by georgik** [comment]
@kassane Thank you for the update.
I've noticed that there is an mistake in `zig/esp-idf-v5/get-started/hello_world/main/CMakeLists.txt` in case of identification of M1 architecture. It should be `arm64`, not `aarch64`.

Also I had to remove the line with ESP-IDF version, because it produces `Invalid Character` crash when built with master.

Here's the correction: https://github.com/georgik/esp32-lang-lab/commit/aca94a6fa3878182c4900d7f85420678e0b63aa8

I've updated the results table. Thank you very much for the contribution.
